// packages/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { nanoid } from 'nanoid';

interface Todo {
  id: string;
  text: string;
}

@Component({
  selector: '#app',
  templateUrl: './app.component.html',
})
export class AppComponent {
  todos: Todo[] = [];

  inputValue: string = '';

  addTodo(event : Event) {
    event.preventDefault();

    this.todos = [
      ...this.todos,
      {
        id: nanoid(),
        text: this.inputValue
      }
    ];

    this.inputValue = '';
  }

  removeTodo(todoId: string) {
    this.todos = this.todos.filter(
      ({ id }) => id !== todoId
    );
  }
}

<div class="todo-container">
  <form class="todo-form" (submit)="addTodo($event)">
    <input
      name="text"
      type="text"
      [(ngModel)]="inputValue"
      placeholder="Add a new task" />
    <button type="submit">OK</button>
  </form>
  <div class="todo" *ngFor="let todo of todos">
    <div class="todo-description">
      <div>{{ todo.text }}</div>
      <small>{{ todo.id }}</small>
    </div>
    <button class="todo-remove" (click)="removeTodo(todo.id)">&times;</button>
  </div>
</div>

// packages/svelte/src/App.svelte
<script>
  import { nanoid } from "nanoid";

  let text = "";

  let todos = [];

  const addTodo = () => {
    todos = [
      ...todos,
      {
        id: nanoid(),
        text,
      },
    ];

    text = "";
  };

  const removeTodo = (todo) => {
    todos = todos.filter(({ id }) => id !== todo.id);
  };
</script>

<div class="todo-container">
  <form on:submit|preventDefault={addTodo} class="todo-form">
    <input
      name="text"
      type="text"
      bind:value={text}
      placeholder="Add a new task" />
    <button type="submit">OK</button>
  </form>
  {#each todos as todo (todo.id)}
    <div class="todo">
      <div class="todo-description">
        <div>{todo.text}</div>
        <small>{todo.id}</small>
      </div>
      <button class="todo-remove" on:click={removeTodo(todo)}> &times; </button>
    </div>
  {/each}
</div>
