// packages/vue-vuex/src/App.vue
<template>
  <div class="todo-container">
    <form @submit.prevent="addTodo" class="todo-form">
      <input name="text" type="text" v-model="text" placeholder="Add a new task" />
      <button type="submit">OK</button>
    </form>
    <div v-for="todo in todos" :key="todo.id" class="todo">
      <div class="todo-description">
        <div>{{ todo.text }}</div>
        <small>{{ todo.id }}</small>
      </div>
      <button class="todo-remove" @click="removeTodo(todo)">
        &times;
      </button>
    </div>
  </div>
</template>

<script>
import { computed, ref } from 'vue'
import { useStore } from 'vuex'

export default {
  name: 'App',

  setup() {
    const store = useStore()
    
    const todos = computed(() => store.state.todos)

    const text = ref('')

    const addTodo = () => {
      store.dispatch(
        'addTodo',
        text.value
      )

      text.value = ''
    }

    const removeTodo = (todo) => {
      store.dispatch(
        'removeTodo',
        todo.id
      )
    }

    return {
      addTodo, 
      removeTodo,
      text,
      todos
    }
  }
}
</script>

// packages/svelte-akita/src/App.svelte
<script>
  import { text, todos, addTodo, removeTodo, setText } from "./store";

  const onAddTodo = () => {
    addTodo(text);
    setText("");
  };

  const onRemoveTodo = (todoId) => {
    removeTodo(todoId);
  };

  const onSetText = (event) => {
    setText(event.target.value);
  };
</script>

<div class="todo-container">
  <form on:submit|preventDefault={onAddTodo} class="todo-form">
    <input
      name="text"
      type="text"
      value={$text}
      on:input|preventDefault={onSetText}
      placeholder="Add a new task" />
    <button type="submit">OK</button>
  </form>
  {#each $todos as todo (todo.id)}
    <div class="todo">
      <div class="todo-description">
        <div>{todo.text}</div>
        <small>{todo.id}</small>
      </div>
      <button class="todo-remove" on:click={onRemoveTodo(todo.id)}>
        &times;
      </button>
    </div>
  {/each}
</div>
