// packages/angular-ngrx/src/app/app.component.ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';

import { State, Todo } from './todo.model';
import { addTodo, removeTodo, setText } from './todo.actions';

@Component({
  selector: '#app',
  templateUrl: './app.component.html',
})
export class AppComponent {
  todos$: Observable<Todo[]>
  text$: Observable<string>

  constructor(private store: Store<{ todo: State }>) {
    this.todos$ = store.select('todo', 'todos')
    this.text$ = store.select('todo', 'text')
  }

  addTodo(event: Event) {
    event.preventDefault();

    this.store.dispatch(addTodo())
  }

  removeTodo(todo: Todo) {
    this.store.dispatch(removeTodo({ todo }))
  }

  setText(text: string) {
    this.store.dispatch(setText({ text }))
  }
}

<div class="todo-container">
  <form class="todo-form" (submit)="addTodo($event)">
    <input
      name="text"
      type="text"
      [value]="text$ | async"
      (input)="setText($event.target.value)"
      placeholder="Add a new task" />
    <button type="submit">OK</button>
  </form>
  <div class="todo" *ngFor="let todo of todos$ | async">
    <div class="todo-description">
      <div>{{ todo.text }}</div>
      <small>{{ todo.id }}</small>
    </div>
    <button class="todo-remove" (click)="removeTodo(todo)">&times;</button>
  </div>
</div>

// packages/svelte-effector/src/App.svelte
<script>
  import { store, addTodo, removeTodo, setText } from "./store";
</script>

<div class="todo-container">
  <form on:submit|preventDefault={addTodo} class="todo-form">
    <input
      name="text"
      type="text"
      value={$store.text}
      on:input={(event) => setText(event.target.value)}
      placeholder="Add a new task" />
    <button type="submit">OK</button>
  </form>
  {#each $store.todos as todo (todo.id)}
    <div class="todo">
      <div class="todo-description">
        <div>{todo.text}</div>
        <small>{todo.id}</small>
      </div>
      <button class="todo-remove" on:click={removeTodo(todo.id)}>
        &times;
      </button>
    </div>
  {/each}
</div>
