// packages/solid/src/App.js
import { createState, produce } from "solid-js"
import { nanoid } from "nanoid"

export default function App() {
  const [state, setState] = createState({
    text: '',
    todos: []
  })

  const onInput = (event) => {
    setState('text', event.target.value)
  }

  const addTodo = (event) => {
    event.preventDefault()

    setState(produce((draftState) => {
      draftState.todos.push({
        id: nanoid(),
        text: draftState.text
      })

      draftState.text = ''
    }))
  }

  const removeTodo = (todo) => {
    setState(produce(draftState => {
      draftState.todos = draftState.todos.filter(
        ({ id }) => id !== todo.id
      )
    }))
  }

  return (
    <div class="todo-container">
      <form onSubmit={addTodo} class="todo-form">
        <input
          name="text"
          type="text"
          value={state.text}
          onInput={onInput}
          placeholder="Add a new task" />
        <button type="submit">OK</button>
      </form>
      {state.todos.map(
        (todo) => (
          <div key={todo.id} class="todo">
            <div class="todo-description">
              <div>{todo.text}</div>
              <small>{todo.id}</small>
            </div>
            <button class="todo-remove" onClick={() => removeTodo(todo)}> &times; </button>
          </div>
        )
      )}
    </div>
  );
}

// packages/vue/src/App.vue
<template>
  <div class="todo-container">
    <form @submit.prevent="addTodo" class="todo-form">
      <input name="text" type="text" v-model="text" placeholder="Add a new task" />
      <button type="submit">OK</button>
    </form>
    <div v-for="todo in todos" :key="todo.id" class="todo">
      <div class="todo-description">
        <div>{{ todo.text }}</div>
        <small>{{ todo.id }}</small>
      </div>
      <button class="todo-remove" @click="removeTodo(todo)">&times;</button>
    </div>
  </div>
</template>

<script>
import { computed, ref } from "vue";
import { nanoid } from "nanoid";

export default {
  name: "App",

  setup() {
    const todos = ref([]);

    const text = ref("");

    const addTodo = () => {
      const newTodo = {
        id: nanoid(),
        text: text.value,
      };

      todos.value = [...todos.value, newTodo];

      text.value = "";
    };

    const removeTodo = (todo) => {
      todos.value = todos.value.filter(({ id }) => id !== todo.id);
    };

    return {
      addTodo,
      removeTodo,
      text,
      todos,
    };
  },
};
</script>
