// packages/svelte-zustand/src/App.svelte
<script>
  import { nanoid } from "nanoid";

  import createStore from "./store.js";

  const store = createStore((set) => ({
    text: "",
    todos: [],
    setText: (text) => set(() => ({ text })),
    addTodo: () =>
      set((state) => ({
        todos: [
          ...state.todos,
          {
            id: nanoid(),
            text: state.text,
          },
        ],
        text: "",
      })),
    removeTodo: (todoId) =>
      set((state) => ({
        todos: state.todos.filter(({ id }) => id !== todoId),
      })),
  }));
</script>

<div class="todo-container">
  <form on:submit|preventDefault={$store.addTodo} class="todo-form">
    <input
      name="text"
      type="text"
      value={$store.text}
      on:change={(event) => $store.setText(event.target.value)}
      placeholder="Add a new task" />
    <button type="submit">OK</button>
  </form>
  {#each $store.todos as todo (todo.id)}
    <div class="todo">
      <div class="todo-description">
        <div>{todo.text}</div>
        <small>{todo.id}</small>
      </div>
      <button class="todo-remove" on:click={$store.removeTodo(todo.id)}>
        &times;
      </button>
    </div>
  {/each}
</div>

// packages/solid/src/App.js
import { createState, produce } from "solid-js"
import { nanoid } from "nanoid"

export default function App() {
  const [state, setState] = createState({
    text: '',
    todos: []
  })

  const onInput = (event) => {
    setState('text', event.target.value)
  }

  const addTodo = (event) => {
    event.preventDefault()

    setState(produce((draftState) => {
      draftState.todos.push({
        id: nanoid(),
        text: draftState.text
      })

      draftState.text = ''
    }))
  }

  const removeTodo = (todo) => {
    setState(produce(draftState => {
      draftState.todos = draftState.todos.filter(
        ({ id }) => id !== todo.id
      )
    }))
  }

  return (
    <div class="todo-container">
      <form onSubmit={addTodo} class="todo-form">
        <input
          name="text"
          type="text"
          value={state.text}
          onInput={onInput}
          placeholder="Add a new task" />
        <button type="submit">OK</button>
      </form>
      {state.todos.map(
        (todo) => (
          <div key={todo.id} class="todo">
            <div class="todo-description">
              <div>{todo.text}</div>
              <small>{todo.id}</small>
            </div>
            <button class="todo-remove" onClick={() => removeTodo(todo)}> &times; </button>
          </div>
        )
      )}
    </div>
  );
}
